/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secure;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static secure.TeacherFrame.flag;

/**
 *
 * @author sooryagangarajk
 */
public class AdminView extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null, pst1 = null;
    ResultSet rs = null;
    public static int selectedSubTRC = 0, selectedSubTRC1 = 0, SSlastRow, SSlastRow1;

    /**
     * Creates new form StudentLogin
     */
    public AdminView() {
        //(new login()).setVisible(true);
        //this.setVisible(false);
        initComponents();
        USA_select.addItem("Student");
        USA_select.addItem("Lecturer");

    }

    public AdminView(boolean b) {
        initComponents();
        this.setVisible(b);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        usrnm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pswd = new javax.swing.JTextField();
        submitbtn3 = new javax.swing.JButton();
        USA_select = new javax.swing.JComboBox<>();
        isAdmin = new javax.swing.JCheckBox();
        usnSid = new javax.swing.JTextField();
        Status1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        phone2 = new javax.swing.JTextField();
        email2 = new javax.swing.JTextField();
        usn2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        add2 = new javax.swing.JTextField();
        stdAddBtn = new javax.swing.JButton();
        name2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        submitbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Class_st = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        stddeleteBtn1 = new javax.swing.JButton();
        status3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        TName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TSID = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Status2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTSS = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTAS = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jF4_SN = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jF5_SC = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        StatusS = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        SectionComboBox = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTAS1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTSS1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        status6 = new javax.swing.JLabel();
        Status7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        LogTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(547, 704));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrator");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Username:");

        usrnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrnmActionPerformed(evt);
            }
        });

        jLabel9.setText("Password:");

        pswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdActionPerformed(evt);
            }
        });

        submitbtn3.setText("Add");
        submitbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtn3ActionPerformed(evt);
            }
        });

        USA_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SID" }));
        USA_select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USA_selectMouseClicked(evt);
            }
        });

        isAdmin.setText("Is Admin?");
        isAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAdminActionPerformed(evt);
            }
        });

        usnSid.setText("Usn or SID");
        usnSid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usnSidMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usnSidMouseEntered(evt);
            }
        });
        usnSid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usnSidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(USA_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitbtn3)
                    .addComponent(pswd)
                    .addComponent(usrnm)
                    .addComponent(isAdmin)
                    .addComponent(usnSid, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addGap(76, 76, 76))
            .addComponent(Status1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usnSid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USA_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(isAdmin)
                .addGap(18, 18, 18)
                .addComponent(submitbtn3)
                .addGap(31, 31, 31)
                .addComponent(Status1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add User", jPanel1);

        jScrollPane1.setViewportView(output);

        jLabel2.setText("USN:");

        phone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone2ActionPerformed(evt);
            }
        });

        email2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email2ActionPerformed(evt);
            }
        });

        usn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usn2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Phone no:");

        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });

        stdAddBtn.setText("Add");
        stdAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdAddBtnActionPerformed(evt);
            }
        });

        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Name:");

        submitbtn.setText("Search");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Email:");

        jLabel5.setText("Address:");

        Class_st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class_stActionPerformed(evt);
            }
        });

        jLabel10.setText("Class:");

        stddeleteBtn1.setText("delete");
        stddeleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stddeleteBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name2)
                            .addComponent(usn2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(stdAddBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stddeleteBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitbtn))
                            .addComponent(email2)
                            .addComponent(add2)
                            .addComponent(phone2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Class_st, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class_st, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdAddBtn)
                    .addComponent(submitbtn)
                    .addComponent(stddeleteBtn1))
                .addContainerGap())
        );

        status3.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(status3, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status3))
        );

        jTabbedPane1.addTab("Add Student", jPanel2);

        TName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNameActionPerformed(evt);
            }
        });

        jLabel11.setText("NAME:");

        jLabel12.setText("SID:");

        TSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSIDActionPerformed(evt);
            }
        });

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Status2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        JTSS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "SUBCODE", "SUB NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTSS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTSSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTSS);

        JTAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "SUBCODE", "SUB NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTASMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JTAS);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Available Subjects:");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Subjects Selected:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TSID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Status2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(53, 53, 53)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Status2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Teacher", jPanel4);

        jLabel17.setText("Subject name:");

        jF4_SN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jF4_SNActionPerformed(evt);
            }
        });

        jLabel18.setText("Subject code:");

        jF5_SC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jF5_SCActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        StatusS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(StatusS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(34, 34, 34)
                            .addComponent(jF4_SN, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(34, 34, 34)
                            .addComponent(jF5_SC, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jF5_SC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jF4_SN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(StatusS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Subjects", jPanel5);

        jPanel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        SectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SectionComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SectionComboBoxMouseEntered(evt);
            }
        });

        JTAS1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "SUBCODE", "SUB NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTAS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTAS1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(JTAS1);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Available Subjects:");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Subjects Selected:");

        JTSS1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "SUBCODE", "SUB NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTSS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTSS1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(JTSS1);

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Status7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(status6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(SectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Status7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(SectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Status7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(status6))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SectionAndSubjects", jPanel6);

        jButton6.setText("Load");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        LogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "SID", "Date and time"
            }
        ));
        jScrollPane6.setViewportView(LogTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Log", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jButton1))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 530, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(223, 223, 223))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usn2ActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed

        conn = MySqlConnect.ConnectDB();

        String Sql = "CALL GetStudentData(?)";
        String usnGot = usn2.getText().toUpperCase();

        try {
            pst = conn.prepareStatement(Sql);
            pst.setString(1, usnGot);

            rs = pst.executeQuery();
            if (rs.next()) {
                String c1 = "" + rs.getString(1) + "\n";
                c1 += "" + rs.getString(2) + "\n";
                c1 += "" + rs.getString(3) + "\n";
                c1 += "" + rs.getString(4) + "\n";
                c1 += "" + rs.getString(5) + "\n";

                output.setText(c1);
            } else {
                JOptionPane.showMessageDialog(null, "USN not found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_submitbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        (new login()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name2ActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add2ActionPerformed

    private void email2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email2ActionPerformed

    private void phone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone2ActionPerformed

    private void stdAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdAddBtnActionPerformed
//Class_st
        try {
            conn = MySqlConnect.ConnectDB();
            String usn = usn2.getText().toUpperCase();
            String name = name2.getText();
            String add = add2.getText();
            String email = email2.getText();
            String phone = phone2.getText();
            String className = Class_st.getText();
            className = className.toUpperCase();
            if (className.equals("1CSEB") || className.equals("1CSEA")
                    || className.equals("2CSEB") || className.equals("2CSEA")
                    || className.equals("3CSEB") || className.equals("3CSEA")
                    || className.equals("4CSEB") || className.equals("4CSEA")
                    || className.equals("5CSEB") || className.equals("5CSEA")
                    || className.equals("6CSEB") || className.equals("6CSEA")
                    || className.equals("7CSEB") || className.equals("7CSEA")
                    || className.equals("8CSEB") || className.equals("8CSEA")) {
                if (add.isEmpty()) {
                    add = "Empty Address";
                }
                if (email.isEmpty()) {
                    email = "Empty Email Address";
                }
                if (phone.isEmpty()) {
                    phone = "Empty Phone Number";
                }
                if (className.isEmpty()) {
                    status3.setText("Class name is empty");
                }
                if (!className.isEmpty()) {

                    String Sql = "INSERT INTO Student_Details ( USN, Name_Of_Student,"
                            + " Permanent_Address, Phone_Number, Email) VALUES ( ?, ?, ?, ?, ?)";
                    String Sql1 = "INSERT INTO StudentAndSections ( USN, Section) VALUES ( ?, ?)";
                    PreparedStatement preparedStmt = conn.prepareStatement(Sql);
                    PreparedStatement preparedStmt1 = conn.prepareStatement(Sql1);
                    preparedStmt.setString(1, usn);
                    preparedStmt.setString(2, name);
                    preparedStmt.setString(3, add);
                    preparedStmt.setString(4, phone);
                    preparedStmt.setString(5, email);

                    preparedStmt1.setString(1, usn);
                    preparedStmt1.setString(2, className);

                    // execute the java preparedstatement
                    preparedStmt.executeUpdate();
                    preparedStmt1.executeUpdate();
                    status3.setText("Student Added");
                }
            } else {
                status3.setText("Incorrect class name");
            }
            ///
        } catch (SQLException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_stdAddBtnActionPerformed

    private void usrnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrnmActionPerformed

    private void pswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdActionPerformed

    private void submitbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtn3ActionPerformed
        try {///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
            //  usnSid
            //  usrnm
            //  pswd
            //  isAdmin
            //  select * from login where username=?
            //  USA_select
            conn = MySqlConnect.ConnectDB();
            String Sql = "select * from Login where UserName=?;";
            String usrNM = usrnm.getText();
            pst = conn.prepareStatement(Sql);
            pst.setString(1, usrNM);

            rs = pst.executeQuery();

            if (rs.next()) {//Update the userPassword

                Sql = "UPDATE Login SET Password = ? WHERE UserName = ?";

                PreparedStatement preparedStmt = conn.prepareStatement(Sql);
                preparedStmt.setString(1, pswd.getText());
                preparedStmt.setString(2, usrNM);

                // execute the java preparedstatement
                preparedStmt.executeUpdate();
                Status1.setText("User password updated");
            } else {
                pst1 = conn.prepareStatement(Sql);
                Status1.setText("");
                if (USA_select.getSelectedItem().toString().equals("USN")) {
                    if (usnSid.getText().isEmpty() | usnSid.getText().equals("Usn or SID")) {
                        Status1.setText("Input USN");
                    } else {//Insert the Student
                        Sql = "INSERT INTO Login (UserName, Password, IsAdmin, USN) VALUES (?, ?, ?, ?)";
                        PreparedStatement preparedStmt = conn.prepareStatement(Sql);
                        preparedStmt.setString(1, usrNM);
                        preparedStmt.setString(2, pswd.getText());
                        preparedStmt.setString(3, "0");
                        preparedStmt.setString(4, usnSid.getText().toUpperCase());
                        // execute the preparedstatement
                        preparedStmt.execute();
                        Status1.setText("Student User added");
                    }
                } else if (USA_select.getSelectedItem().toString().equals("SID")) {
                    if (usnSid.getText().isEmpty() | usnSid.getText().equals("Usn or SID")) {
                        Status1.setText("Input SID");
                    } else {//Insert the Teacher
                        Sql = "INSERT INTO Login (UserName, Password, IsAdmin, SID) VALUES (?, ?, ?, ?)";
                        if (isAdmin.isSelected()) {

                            PreparedStatement preparedStmt = conn.prepareStatement(Sql);
                            preparedStmt.setString(1, usrNM);
                            preparedStmt.setString(2, pswd.getText());
                            preparedStmt.setString(3, "1");
                            preparedStmt.setString(4, usnSid.getText().toUpperCase());

                            // execute the preparedstatement
                            preparedStmt.execute();
                            Status1.setText("Teacher(Admin) added");
                        } else {
                            {
                                PreparedStatement preparedStmt = conn.prepareStatement(Sql);
                                preparedStmt.setString(1, usrNM);
                                preparedStmt.setString(2, pswd.getText());
                                preparedStmt.setString(3, "0");
                                preparedStmt.setString(4, usnSid.getText().toUpperCase());

                                // execute the preparedstatement
                                preparedStmt.execute();
                                Status1.setText("Teacher added");
                            }
                        }
                    }
                } else {
                    Status1.setText("");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
            Status1.setText("Invalid SID");
        }


    }//GEN-LAST:event_submitbtn3ActionPerformed

    private void isAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isAdminActionPerformed

    private void usnSidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usnSidMouseEntered


    }//GEN-LAST:event_usnSidMouseEntered

    private void usnSidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usnSidMouseClicked
        usnSid.setText("");
    }//GEN-LAST:event_usnSidMouseClicked

    private void USA_selectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USA_selectMouseClicked

    }//GEN-LAST:event_USA_selectMouseClicked

    private void Class_stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class_stActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Class_stActionPerformed

    private void stddeleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stddeleteBtn1ActionPerformed

        try {
            conn = MySqlConnect.ConnectDB();
            String query = "DELETE FROM StudentAndSections WHERE USN=?;";
            String query1 = "DELETE FROM Student_Details WHERE USN=?;";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            PreparedStatement preparedStmt1 = conn.prepareStatement(query1);
            preparedStmt.setString(1, usn2.getText());
            preparedStmt.execute();
            preparedStmt1.setString(1, usn2.getText());
            preparedStmt1.execute();
            System.out.println("Student Deleted");
            status3.setText("Student Deleted");
        } catch (SQLException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_stddeleteBtn1ActionPerformed

    private void usnSidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usnSidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usnSidActionPerformed

    private void TNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNameActionPerformed

    private void TSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TSIDActionPerformed

    private void jF4_SNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jF4_SNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jF4_SNActionPerformed

    private void jF5_SCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jF5_SCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jF5_SCActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            conn = MySqlConnect.ConnectDB();
            String Sql = "DELETE FROM SUBJECTS WHERE SUB_Code=?;";

            PreparedStatement preparedStmt = conn.prepareStatement(Sql);
            preparedStmt.setString(1, jF5_SC.getText());

            preparedStmt.executeUpdate();
            StatusS.setText("DELETED");
        } catch (SQLException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            boolean existFlag = false;

            conn = MySqlConnect.ConnectDB();
            String Sql = "select * from StaffDetails where SID=?;";
            String tSID = TSID.getText();
            pst = conn.prepareStatement(Sql);
            pst.setString(1, tSID);

            rs = pst.executeQuery();

            if (rs.next()) {
                existFlag = true;
                Sql = "UPDATE StaffDetails SET Name=?  WHERE  SID = ?";

                PreparedStatement preparedStmt = conn.prepareStatement(Sql);
                preparedStmt.setString(1, TName.getText());
                preparedStmt.setString(2, TSID.getText().toUpperCase());

                preparedStmt.executeUpdate();

            } else {
                existFlag = false;
                Sql = "INSERT INTO StaffDetails (Name,SID) VALUES (?, ?);";

                PreparedStatement preparedStmt = conn.prepareStatement(Sql);
                preparedStmt.setString(1, TName.getText());
                preparedStmt.setString(2, TSID.getText().toUpperCase());

                preparedStmt.executeUpdate();

            }

            String subjectCode = "", SIDSTR = TSID.getText().toUpperCase();
            int i = 0;
            if (existFlag) {
                Sql = "DELETE FROM Subject_And_SID WHERE SID=?;";
                PreparedStatement preparedStmt = conn.prepareStatement(Sql);

                preparedStmt.setString(1, TSID.getText().toUpperCase());

                preparedStmt.executeUpdate();

            }
            while (i < selectedSubTRC) {

                Sql = "INSERT INTO Subject_And_SID (SID,SUB_Code) VALUES (?, ?);";
                PreparedStatement preparedStmt = conn.prepareStatement(Sql);
                preparedStmt.setString(1, SIDSTR);
                subjectCode = (String) JTSS.getModel().getValueAt(i, 0);
                //System.out.println("::::::::::"+subjectCode);
                preparedStmt.setString(2, subjectCode);

                preparedStmt.executeUpdate();
                i++;
            }
            if (i == selectedSubTRC && existFlag) {
                Status2.setText("Teacher details updated");
            } else if (i == selectedSubTRC && !existFlag) {
                Status2.setText("Teacher details inserted");
            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (!jF5_SC.getText().isEmpty() && !jF4_SN.getText().isEmpty()) {
            try {
                //jF5_SC  jF4_SN
                conn = MySqlConnect.ConnectDB();
                String Sql = "INSERT INTO SUBJECTS ( SUB_Code, SUB_NM) VALUES (?,?)";
                PreparedStatement preparedStmt = conn.prepareStatement(Sql);
                preparedStmt.setString(1, jF5_SC.getText().toUpperCase());
                preparedStmt.setString(2, jF4_SN.getText());

                // execute the java preparedstatement
                preparedStmt.executeUpdate();
                StatusS.setText("Subject Added");
            } catch (SQLException ex) {
                Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
                StatusS.setText("Subject already added");
            }
        } else {
            StatusS.setText("Subject name or Subject code field is empty");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered

// Load all subjects
        JTAS.setDefaultEditor(Object.class, null);//Disables Editing
        JTSS.setDefaultEditor(Object.class, null);//Disables Editing
        System.out.println("loadData loading...");

        conn = MySqlConnect.ConnectDB();
///select Name_Of_Student,USN from Student_Details where CLASS='CSE5B' order by USN ;

        String Sql = "select * from SUBJECTS";
        try {
            pst = conn.prepareStatement(Sql);
            rs = pst.executeQuery();
            int rowCount = 0;
            DefaultTableModel model = (DefaultTableModel) JTAS.getModel();
            while (rs.next()) {
                String column1 = rs.getString(1);
                String column2 = rs.getString(2);
                System.out.println(column1 + "" + column2);

                model.setRowCount(rowCount + 1);
                if (JTSS.getModel() != null) {
                    JTAS.getModel().setValueAt(column1, rowCount, 0);
                }
                JTAS.getModel().setValueAt(column2, rowCount, 1);

                rowCount++;
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }


    }//GEN-LAST:event_jLabel14MouseEntered

    private void JTASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTASMouseClicked
        int i = JTAS.getSelectedRow();
        System.out.println("Clicked");
        addToASTable(JTAS.getSelectedRow(), i);
    }//GEN-LAST:event_JTASMouseClicked

    private void JTSSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTSSMouseClicked
        // TODO add your handling code here:

        if (selectedSubTRC != 0) {
            selectedSubTRC--;
        }
        ((DefaultTableModel) JTSS.getModel()).removeRow(JTSS.getSelectedRow());
    }//GEN-LAST:event_JTSSMouseClicked

    private void JTAS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTAS1MouseClicked

        int i = JTAS1.getSelectedRow();
        System.out.println("Clicked");
        addToASTable1(JTAS1.getSelectedRow(), i);
    }//GEN-LAST:event_JTAS1MouseClicked

    private void JTSS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTSS1MouseClicked

        if (selectedSubTRC1 != 0) {
            selectedSubTRC1--;
        }
        ((DefaultTableModel) JTSS1.getModel()).removeRow(JTSS1.getSelectedRow());
    }//GEN-LAST:event_JTSS1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // delete the all the subjects of a section
            conn = MySqlConnect.ConnectDB();
            String Sql = "DELETE FROM SUBJECTS_AND_SECTIONS WHERE Section=?;";
            PreparedStatement preparedStmt = conn.prepareStatement(Sql);

            preparedStmt.setString(1, (String) SectionComboBox.getSelectedItem());

            preparedStmt.executeUpdate();
// update the sections and subjects using while loop

            int i = 0;
            String subjectCode = "";
            while (i < selectedSubTRC1) {

                Sql = "INSERT INTO SUBJECTS_AND_SECTIONS (SUB_Code, Section) VALUES (?, ?);";
                PreparedStatement preparedStmt1 = conn.prepareStatement(Sql);

                subjectCode = (String) JTSS1.getModel().getValueAt(i, 0);
                preparedStmt1.setString(2, (String) SectionComboBox.getSelectedItem());
                preparedStmt1.setString(1, subjectCode);
                
                preparedStmt1.executeUpdate();
                i++;
                //System.out.println("I="+i+"selectedSubTRC:"+selectedSubTRC);
            }
            if (true) {
                Status7.setText("Section " + SectionComboBox.getSelectedItem() + " updated");
            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered

        JTAS1.setDefaultEditor(Object.class, null);//Disables Editing
        JTSS1.setDefaultEditor(Object.class, null);//Disables Editing
        System.out.println("loadData loading...");

        conn = MySqlConnect.ConnectDB();
///select Name_Of_Student,USN from Student_Details where CLASS='CSE5B' order by USN ;

        String Sql = "select * from SUBJECTS";
        try {
            pst = conn.prepareStatement(Sql);
            rs = pst.executeQuery();
            int rowCount = 0;
            DefaultTableModel model = (DefaultTableModel) JTAS1.getModel();
            while (rs.next()) {
                String column1 = rs.getString(1);
                String column2 = rs.getString(2);
                System.out.println(column1 + "" + column2);

                model.setRowCount(rowCount + 1);
                if (JTSS1.getModel() != null) {
                    JTAS1.getModel().setValueAt(column1, rowCount, 0);
                }
                JTAS1.getModel().setValueAt(column2, rowCount, 1);

                rowCount++;
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_jLabel13MouseEntered

    private void SectionComboBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SectionComboBoxMouseEntered
        Vector comboBoxItems = new Vector();
        String Sql1 = "select * from Section;";
        comboBoxItems = new Vector();
        conn = MySqlConnect.ConnectDB();
        try {
            Statement st = conn.createStatement();

            rs = st.executeQuery(Sql1);
            while (rs.next()) {
                // status.setText(status.getText()+"\n"+rs.getString(1));
                comboBoxItems.add(rs.getString(1));

            }

        } catch (Exception e) {

        }

        final DefaultComboBoxModel model2 = new DefaultComboBoxModel(comboBoxItems);
        SectionComboBox.setModel(model2);

    }//GEN-LAST:event_SectionComboBoxMouseEntered

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        
        //LogTable
        
         LogTable.setDefaultEditor(Object.class, null);//Disables Editing
        LogTable.setDefaultEditor(Object.class, null);//Disables Editing
        System.out.println("LogData loading...");

        conn = MySqlConnect.ConnectDB();
///select Name_Of_Student,USN from Student_Details where CLASS='CSE5B' order by USN ;

        String Sql = "select * from Log";
        try {
            pst = conn.prepareStatement(Sql);
            rs = pst.executeQuery();
            int rowCount = 0;
            DefaultTableModel model = (DefaultTableModel) LogTable.getModel();
            while (rs.next()) {
                String column1 = rs.getString(1);
                String column2 = rs.getString(2);
                System.out.println(column1 + "" + column2);

                model.setRowCount(rowCount + 1);
                if (LogTable.getModel() != null) {
                    LogTable.getModel().setValueAt(column1, rowCount, 0);
                }
                LogTable.getModel().setValueAt(column2, rowCount, 1);

                rowCount++;
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }



    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(false);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Class_st;
    private javax.swing.JTable JTAS;
    private javax.swing.JTable JTAS1;
    private javax.swing.JTable JTSS;
    private javax.swing.JTable JTSS1;
    private javax.swing.JTable LogTable;
    private javax.swing.JComboBox<String> SectionComboBox;
    private javax.swing.JLabel Status1;
    private javax.swing.JLabel Status2;
    private javax.swing.JLabel Status7;
    private javax.swing.JLabel StatusS;
    private javax.swing.JTextField TName;
    private javax.swing.JTextField TSID;
    private javax.swing.JComboBox<String> USA_select;
    private javax.swing.JTextField add2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField email2;
    private javax.swing.JCheckBox isAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField jF4_SN;
    private javax.swing.JTextField jF5_SC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name2;
    private javax.swing.JTextPane output;
    private javax.swing.JTextField phone2;
    private javax.swing.JTextField pswd;
    private javax.swing.JLabel status3;
    private javax.swing.JLabel status6;
    private javax.swing.JButton stdAddBtn;
    private javax.swing.JButton stddeleteBtn1;
    private javax.swing.JButton submitbtn;
    private javax.swing.JButton submitbtn3;
    private javax.swing.JTextField usn2;
    private javax.swing.JTextField usnSid;
    private javax.swing.JTextField usrnm;
    // End of variables declaration//GEN-END:variables
private void addToASTable(int selectedRow, int i) {/////////////////////////////////////////////////
        if (SSlastRow != i) {
            DefaultTableModel model = (DefaultTableModel) JTSS.getModel();
            SSlastRow = i;
            model.setRowCount(selectedSubTRC + 1);
            String c1 = (String) JTAS.getModel().getValueAt(selectedRow, 0);
            String c2 = (String) JTAS.getModel().getValueAt(selectedRow, 1);
            JTSS.getModel().setValueAt(c1, selectedSubTRC, 0);
            JTSS.getModel().setValueAt(c2, selectedSubTRC, 1);
            selectedSubTRC++;
        }
    }

    private void addToASTable1(int selectedRow, int i) {/////////////////////////////////////////////////
        if (SSlastRow1 != i) {
            DefaultTableModel model = (DefaultTableModel) JTSS1.getModel();
            SSlastRow1 = i;
            model.setRowCount(selectedSubTRC1 + 1);
            String c1 = (String) JTAS1.getModel().getValueAt(selectedRow, 0);
            String c2 = (String) JTAS1.getModel().getValueAt(selectedRow, 1);
            JTSS1.getModel().setValueAt(c1, selectedSubTRC1, 0);
            JTSS1.getModel().setValueAt(c2, selectedSubTRC1, 1);
            selectedSubTRC1++;
        }
    }
}
